name: Build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Build with ESP-IDF v6.0
        uses: espressif/esp-idf-ci-action@v1
        with:
          esp_idf_version: v6.0.2
          target: esp32s3
          path: "."
